// Angular/lab3/src/app/components/register/register.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Output } from '@angular/core';
import Student from '../../Utils/Student';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [FormsModule, CommonModule],
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
})
export class RegisterComponent {
  id: number = 0;
  name: string = '';
  age: number | undefined = undefined;

  std: any = {};

  validName: boolean = true;
  validAge: boolean = true;

  @Output() toParent = new EventEmitter();

  addStudent() {
    this.std.id = Math.floor(Math.random() * 100) + 1;
    this.std.name = this.name;
    this.std.age = this.age;

    this.validName = this.name.length >= 3;
    this.validAge = this.age !== undefined && this.age >= 15 && this.age <= 25;

    if (this.validName && this.validAge) {
      this.toParent.emit(this.std);
      // console.log(this.std);
      this.std = {};
    }
  }
}

<div class="container">
  <div class="form">
    <div>
      <img src="assets/logo.png" alt="logo" width="92" height="92" />
    </div>

    <div class="input-field">
      <input type="text" name="name" [(ngModel)]="name" autocomplete="off" />
      <label>Name</label>
    </div>

    <div *ngIf="validName; else falseBlock1"></div>
    <ng-template #falseBlock1>
      <p style="color: #ff7270">Name should be at least 3 characters long</p>
    </ng-template>

    <div class="input-field">
      <input type="number" name="age" [(ngModel)]="age" autocomplete="off" />
      <label>Age</label>
    </div>

    <div *ngIf="validAge; else falseBlock2"></div>
    <ng-template #falseBlock2>
      <p style="color: #ff7270">Age should be between 15 and 25</p>
    </ng-template>

    <button (click)="addStudent()">Add Student</button>

    <div class="register">
      <p>
        © Created by :
        <a
          class="copyright"
          href="https://github.com/ahmedalam98"
          target="_blank"
          >Ahmed Alam El-Deen</a
        >
      </p>
    </div>
  </div>
</div>

// React/lab3/src/Components/Register/Register.jsx
import React, { useState, useEffect } from "react";
import "./Register.css";

const Register = ({ onAddStudent }) => {
  const [name, setName] = useState("");
  const [age, setAge] = useState("");
  const [validName, setValidName] = useState(null);
  const [validAge, setValidAge] = useState(null);
  const [submitted, setSubmitted] = useState(false);

  useEffect(() => {
    if (submitted) {
      if (name.length >= 3) {
        setValidName(true);
      } else {
        setValidName(false);
      }

      if (age >= 15 && age <= 25) {
        setValidAge(true);
      } else {
        setValidAge(false);
      }
    }
  }, [name, age, submitted]);

  const addStudent = (e) => {
    e.preventDefault();
    setSubmitted(true);
    if (validName && validAge) {
      const id = Math.floor(Math.random() * 100) + 1;
      const student = { id, name, age };
      onAddStudent(student);
      setName("");
      setAge("");
    }
  };

  return (
    <form className="container" onSubmit={addStudent}>
      <div className="form">
        <div>
          <img src="/src/assets/logo.png" alt="logo" width="80" height="80" />
        </div>

        <div className="input-field">
          <input
            type="text"
            name="name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            autoComplete="off"
          />
          <label>Name</label>
        </div>

        {submitted && validName === false && (
          <p style={{ color: "#ff7270" }}>
            Name should be at least 3 characters long
          </p>
        )}

        <div className="input-field">
          <input
            type="number"
            name="age"
            value={age}
            onChange={(e) => setAge(e.target.value)}
            autoComplete="off"
          />
          <label>Age</label>
        </div>

        {submitted && validAge === false && (
          <p style={{ color: "#ff7270" }}>Age should be between 15 and 25</p>
        )}

        <button type="submit">Add Student</button>
      </div>
    </form>
  );
};

export default Register;
