// Angular/lab3/src/app/components/table/table.component.ts
import { Component, Input } from '@angular/core';
import user from '../../Utils/user';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-table',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './table.component.html',
  styleUrl: './table.component.css',
})
export class TableComponent {
  @Input() allusers: user[] = [];
}

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
    </tr>
  </thead>
  <tbody>
    <ng-container *ngIf="allStudents.length === 0">
      <tr>
        <td colspan="2">
          <h3 style="text-align: center; margin: 24px">
            No students added yet, Please use the form
          </h3>
        </td>
      </tr>
    </ng-container>

    <tr *ngFor="let student of allStudents">
      <td>{{ student.name }}</td>
      <td>{{ student.age }}</td>
    </tr>
  </tbody>
</table>

// React/lab3/src/Components/Table/Table.jsx
import React from "react";
import "./Table.css";

const Table = ({ allStudents }) => {
  return (
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Age</th>
        </tr>
      </thead>
      <tbody>
        {allStudents.length === 0 ? (
          <tr>
            <td colSpan="2">
              <h3>No students added yet, Please use the form</h3>
            </td>
          </tr>
        ) : (
          allStudents.map((student) => (
            <tr key={student.id}>
              <td>{student.name}</td>
              <td>{student.age}</td>
            </tr>
          ))
        )}
      </tbody>
    </table>
  );
};

export default Table;
